steps:
  # 步驟1：啟動 Docker-In-Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['docker', 'info']
    env:
      - DOCKER_HOST=unix:///var/run/docker.sock

  # 步驟2：安裝 docker-compose
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --no-cache curl
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

  # 步驟3：使用 docker-compose 啟動服務
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'docker-compose'
    args: ['up', '-d']
